# Generated by Django 4.2.3 on 2024-01-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book_API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BookObject',
        ),
    ]
